In [1]:
# Pythonic Solutions
# the following functions are the steps involved in forward elimination

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

# <font color = red> ASSIGNMENT 1</font>
- The above python functions are developed to automate forward elimination.
- To complete the process of determining the solution, create a function or steps of function that will automate backward substitution.

In [ ]:
def BackwardSubstitution(A, b):
    n = A.shape[0]
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        sum_ax = 0
        for j in range(i+1, n):
            sum_ax += A[i, j] * x[j]
        x[i] = (b[i] - sum_ax) / A[i, i]

    return x


In [2]:
import numpy as np
# Pythonic Solutions
# the following functions are the steps involved in forward elimination

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is    number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

def BackwardSubstitution(A, b):
    n = A.shape[0]
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        sum_ax = 0
        for j in range(i+1, n):
            sum_ax += A[i, j] * x[j]
        x[i] = (b[i] - sum_ax) / A[i, i]

    return x

A=np.array([[1,-1,1,3],[2,1,8,18],[4,2,-3,-2]])

## Add -2 times row 0 to row 1
A1 = RowAdd(A,0,1,-2)
print("A1")
print(A1,'\n')

## Add -4 times row 0 to row 2
A2 = RowAdd(A1,0,2,-4)
print("A2")
print(A2,'\n')

## Add -2 times row 1 to row 2
A3 = RowAdd(A2,1,2,-2)
print("A3")
print(A3,'\n')

## Multiply row 1 by 1/3
A4 = RowScale(A3,1,1.0/3)
print("A4")
print(A4,'\n')

## Multiply row 2 by 1/19
A5 = RowScale(A4,2,1.0/-19.)
print("A5")
print(A5,'\n')
print("Use your assignment for the backward substitution to find the solutions.")

solutions = BackwardSubstitution(A5, np.array([3,4,2]))
# Print the solutions
for i, sol in enumerate(solutions):
    print(f"x{i + 1} = {sol}")


A1
[[ 1. -1.  1.  3.]
 [ 0.  3.  6. 12.]
 [ 4.  2. -3. -2.]] 

A2
[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   6.  -7. -14.]] 

A3
[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   0. -19. -38.]] 

A4
[[  1.  -1.   1.   3.]
 [  0.   1.   2.   4.]
 [  0.   0. -19. -38.]] 

A5
[[ 1. -1.  1.  3.]
 [ 0.  1.  2.  4.]
 [-0. -0.  1.  2.]] 

Use your assignment for the backward substitution to find the solutions.
x1 = 1.0
x2 = 0.0
x3 = 2.0


# <font color = red> Assignment 2 </font>
---
**INSTRUCTION**
- Use latex programming to show your manual solutions.
- If the problem involves determining the row echelon or reduced row echelon, show both the manual and the pythonic solutions.
- Solutions must be saved as a jupyter notebook.
- Push your solutions to your forked github repo.
- Note that there is some **possibility** that some ,or all, of your exam questions will be taken from these assignment.
- The technique here is to first solve manually before writing in Latex.
---

1. Provide reasons why each of the following equations is, or is not, a linear equation.
- $\cos{\theta}x+4y+z = \sqrt{3}$
- $cos{x}4y+z = \sqrt{3}$
- $x^{-1}+7y+z = \sin{(\frac{\pi}{2})}$
- $x^1+y^1+z^1=0$
---

1. $\cos{\theta}x+4y+z = \sqrt{3}$:
   - This equation is not linear because it contains the trigonometric function $\cos{\theta}$. In a linear equation, variables should appear to the first power without any trigonometric functions applied to them.

2. $\cos{x}4y+z = \sqrt{3}$:
   - Similar to the first equation, this equation is also not linear because it contains the trigonometric function $\cos{x}$. Linear equations should involve variables raised only to the first power without trigonometric functions.

3. $x^{-1}+7y+z = \sin{(\frac{\pi}{2})}$:
   - This equation is not linear because it contains the variable $x$ raised to the power of -1, which is equivalent to $\frac{1}{x}$. Linear equations should have variables raised only to the first power, and in this case, the variable $x$ is raised to a power other than 1.

4. $x^1+y^1+z^1=0$:
   - This equation is linear. While it may seem unusual to write $x^1$, $y^1$, and $z^1$ explicitly, they are still raised to the first power, and there are no products, powers other than 1, or trigonometric functions applied to the variables. Therefore, this equation is linear.


2. Find the solutions to the linear equations:
- $2x_1+3x_2 =5$
- $4x_1+3x_2+2x_3=1$
- $3x-6y=0$
---


Manual Solution (LaTeX):

Forward Elimination:
\begin{align*}
2x_1 + 3x_2 &= 5 \\
-2x_1 + 2x_2 &= 0 \\
2x_2 &= 5 \\
x_2 &= \frac{5}{2}
\end{align*}

Backward Substitution:
\begin{align*}
x_1 - 0 &= 0 \\
x_1 &= 0
\end{align*}


In [6]:
import sympy as sp

x1, x2 = sp.symbols('x1 x2')
eq1 = sp.Eq(2*x1 + 3*x2, 5)
sol1 = sp.solve(eq1, (x1, x2))
print(sol1)


[(5/2 - 3*x2/2, x2)]


Manual Solution (LaTeX):

Forward Elimination:
\begin{align*}
4x_1 + 3x_2 + 2x_3 &= 1 \\
-4x_1 + 3x_2 + 2x_3 &= 0 \\
0x_1 + 6x_2 + 0x_3 &= 1
\end{align*}

Simplify:
\begin{align*}
6x_2 &= 1 \\
x_2 &= \frac{1}{6}
\end{align*}

Backward Substitution:
\begin{align*}
0x_1 + 0x_2 + 0x_3 &= 0 \\
0 &= 0
\end{align*}

There is no unique solution for $x_1$ and $x_3$ in this case since there are infinitely many solutions with $x_2 = \frac{1}{6}$.


In [8]:
import sympy as sp
x1, x2, x3 = sp.symbols('x1 x2 x3')
eq2 = sp.Eq(4*x1 + 3*x2 + 2*x3, 1)
sol2 = sp.solve(eq2, (x1, x2, x3))
print(sol2)


[(-3*x2/4 - x3/2 + 1/4, x2, x3)]


Manual Solution (LaTeX):

Forward Elimination:
\begin{align*}
3x - 6y &= 0 \\
3x &= 6y \\
x &= 2y
\end{align*}

Backward Substitution:
\begin{align*}
2y - 6y &= 0 \\
-4y &= 0 \\
y &= 0
\end{align*}

So, the solution is:
\begin{align*}
x &= 2y \\
x &= 2(0) \\
x &= 0
\end{align*}

The solution to the equation is $x = 0$ and $y = 0$.


In [10]:
import sympy as sp
x, y = sp.symbols('x y')
eq3 = sp.Eq(3*x - 6*y, 0)
sol3 = sp.solve(eq3, (x, y))
print(sol3)


[(2*y, y)]


3. Solve the following systems of linear equations<br>
a.<br> 
\begin{equation}
x-y=0 \\
2x+y = 3
\end{equation}
<br>
<br>
b. <br>
\begin{equation}
x+5y= -1 \\
-x+y = -5 \\
2x+4y = 4
\end{equation}
c. <br>
\begin{equation}
2x_1+3x_2-x_3= -1 \\
x_1+x_3 = 0 \\
-x_1+2x_2-2x_3 = 0
\end{equation}
<br>

a.<br> 
\begin{equation}
x-y=0 \\
2x+y = 3
\end{equation}
<br>
Manual Solution (LaTeX):

Forward Elimination:
\begin{align*}
x - y &= 0 \\
2x + y &= 3
\end{align*}

Let's add the two equations to eliminate $y$:
\begin{align*}
(x - y) + (2x + y) &= 0 + 3 \\
3x &= 3 \\
x &= 1
\end{align*}

Now that we have the value of $x$, we can substitute it into the first equation to find $y$:
\begin{align*}
1 - y &= 0 \\
-y &= -1 \\
y &= 1
\end{align*}

So, the solution to the system of equations is:
\begin{align*}
x &= 1 \\
y &= 1
\end{align*}


In [12]:
import sympy as sp

x, y = sp.symbols('x y')
eq1 = sp.Eq(x - y, 0)
eq2 = sp.Eq(2*x + y, 3)
sol = sp.solve((eq1, eq2), (x, y))
print(sol)


{x: 1, y: 1}


b. <br>
\begin{equation}
x+5y= -1 \\
-x+y = -5 \\
2x+4y = 4
\end{equation}
<br>
Manual Solution (LaTeX):

Forward Elimination:

Let's start by adding equations (1) and (2) to eliminate $x$:
\begin{align*}
(x + 5y) + (-x + y) &= (-1) + (-5) \\
6y &= -6 \\
y &= -1
\end{align*}

Now that we have the value of $y$, we can substitute it back into equation (2) to find $x$:
\begin{align*}
-x + (-1) &= -5 \\
-x - 1 &= -5 \\
-x &= -4 \\
x &= 4
\end{align*}

Now that we have found the values of $x$ and $y$, we can substitute them into equation (3) to check:

\begin{align*}
2x + 4y &= 4 \\
2(4) + 4(-1) &= 4 \\
8 - 4 &= 4 \\
4 &= 4
\end{align*}

So, the solution to the system of equations is:
\begin{align*}
x &= 4 \\
y &= -1
\end{align*}


In [13]:
import sympy as sp
x, y = sp.symbols('x y')
eq1 = sp.Eq(x + 5*y, -1)
eq2 = sp.Eq(-x + y, -5)
eq3 = sp.Eq(2*x + 4*y, 4)
sol = sp.solve((eq1, eq2, eq3), (x, y))
print(sol)


{x: 4, y: -1}


c. <br>
\begin{equation}
2x_1+3x_2-x_3= -1 \\
x_1+x_3 = 0 \\
-x_1+2x_2-2x_3 = 0
\end{equation}
<br>
Manual Solution (LaTeX):

Forward Elimination:

Let's start by using equation (2) to isolate $x_1$:
\begin{align*}
x_1 + x_3 &= 0 \\
x_1 &= -x_3
\end{align*}

Now, substitute this expression for $x_1$ into equations (1) and (3):

For equation (1):
\begin{align*}
2(-x_3) + 3x_2 - x_3 &= -1 \\
-2x_3 + 3x_2 - x_3 &= -1 \\
-3x_3 + 3x_2 &= -1 \\
-3(x_3 - x_2) &= -1 \\
x_3 - x_2 &= \frac{1}{3}
\end{align*}

For equation (3):
\begin{align*}
-x_1 + 2x_2 - 2x_3 &= 0 \\
-(-x_3) + 2x_2 - 2x_3 &= 0 \\
x_3 + 2x_2 - 2x_3 &= 0 \\
2x_2 - x_3 &= 0 \\
2x_2 &= x_3
\end{align*}

Now, we have two equations:
1. $x_3 - x_2 = \frac{1}{3}$
2. $2x_2 = x_3$

We can solve this system of equations to find $x_2$ and $x_3$. Let's solve equation (2) for $x_3$ and substitute it into equation (1):

From equation (2):
\begin{align*}
2x_2 &= x_3 \\
x_3 &= 2x_2
\end{align*}

Substitute into equation (1):
\begin{align*}
(2x_2) - x_2 &= \frac{1}{3} \\
x_2 &= \frac{1}{3}
\end{align*}

Now, find $x_3$ using equation (2):
\begin{align*}
x_3 &= 2\left(\frac{1}{3}\right) \\
x_3 &= \frac{2}{3}
\end{align*}

Finally, substitute the values of $x_2$ and $x_3$ back into the expression for $x_1$ from equation (2):
\begin{align*}
x_1 &= -x_3 \\
x_1 &= -\frac{2}{3}
\end{align*}

So, the solution to the system of equations is:
\begin{align*}
x_1 &= -\frac{2}{3} \\
x_2 &= \frac{1}{3} \\
x_3 &= \frac{2}{3}
\end{align*}


In [14]:
import sympy as sp
x1, x2, x3 = sp.symbols('x1 x2 x3')
eq1 = sp.Eq(2*x1 + 3*x2 - x3, -1)
eq2 = sp.Eq(x1 + x3, 0)
eq3 = sp.Eq(-x1 + 2*x2 - 2*x3, 0)
sol = sp.solve((eq1, eq2, eq3), (x1, x2, x3))
print(sol)


{x1: -2/3, x2: 1/3, x3: 2/3}



---
4. Provide reasons why the given matrices are either a row echelon, a reduced row echelon, or niether both.<br>
a. <br>
\begin{pmatrix}
   1 & 0 & 1 \\
   0 & 0 & 3 \\
   0 & 1 & 0 \\
\end{pmatrix}<br><br>
b. <br>
\begin{pmatrix}
   7 & 0 & 1 & 0 \\
   0 & 1 & -1 & 4 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}<br><br>
c. <br>
\begin{pmatrix}
   0 & 1 & 3 & 0 \\
   0 & 0 & 0 & 1 \\
\end{pmatrix}<br><br>
d. <br>
\begin{pmatrix}
   0 & 0 & 0 \\
   0 & 0 & 0 \\
   0 & 0 & 0 \\
\end{pmatrix}<br><br>
e. <br>
\begin{pmatrix}
   1 & 0 & 3 & -4 & 0 \\
   0 & 0 & 0 & 0 & 0 \\
   0 & 1 & 5 & 0 & 1 \\
\end{pmatrix}<br><br>
f. <br>
\begin{pmatrix}
   0 & 0 & 1 \\
   0 & 1 & 0 \\
   1 & 0 & 0 \\
\end{pmatrix}<br><br>
g. <br>
\begin{pmatrix}
   1 & 2 & 3 \\
   1 & 0 & 0 \\
   0 & 1 & 1 \\
   0 & 0 & 1 \\
\end{pmatrix}<br><br>
h. <br>
\begin{pmatrix}
   2 & 1 & 3 & 5 \\
   0 & 0 & 1 & -1 \\
   0 & 0 & 0 & 3 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}
<br><br>


$\textbf{a. Matrix A:}$
\[
\begin{pmatrix}
1 & 0 & 1 \\
0 & 0 & 3 \\
0 & 1 & 0 \\
\end{pmatrix}
\]

This matrix is in $\textbf{row echelon form (REF)}$ because it satisfies the following conditions:
1. In each row, the leftmost nonzero entry is 1.
2. The leading 1 in each row is to the right of the leading 1 in the row above.
3. Rows containing only zeros, if any, are at the bottom.

$\textbf{b. Matrix B:}$
\[
\begin{pmatrix}
7 & 0 & 1 & 0 \\
0 & 1 & -1 & 4 \\
0 & 0 & 0 & 0 \\
\end{pmatrix}
\]

This matrix is in $\textbf{row echelon form (REF)}$ because it satisfies the conditions of REF mentioned above. However, it is not in $\textbf{reduced row echelon form (RREF)}$ because it does not satisfy the additional condition for RREF, which requires that in each column containing a leading 1, all other entries in that column are zeros.

$\textbf{c. Matrix C:}$
\[
\begin{pmatrix}
0 & 1 & 3 & 0 \\
0 & 0 & 0 & 1 \\
\end{pmatrix}
\]

This matrix is in $\textbf{neither row echelon form (REF) nor reduced row echelon form (RREF)}$. In row echelon form, all zero rows should be at the bottom, but in this matrix, they are not. Additionally, in reduced row echelon form, the leading 1 in each row should be the only nonzero entry in its column, which is not the case here.

$\textbf{d. Matrix D:}$
\[
\begin{pmatrix}
0 & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 0 \\
\end{pmatrix}
\]

This matrix is in $\textbf{neither row echelon form (REF) nor reduced row echelon form (RREF)}$ because it consists of all zero rows, and there are no leading 1s.

$\textbf{e. Matrix E:}$
\[
\begin{pmatrix}
1 & 0 & 3 & -4 & 0 \\
0 & 0 & 0 & 0 & 0 \\
0 & 1 & 5 & 0 & 1 \\
\end{pmatrix}
\]

This matrix is in $\textbf{neither row echelon form (REF) nor reduced row echelon form (RREF)}$. While it has leading 1s in rows 1 and 3, it does not satisfy the condition that all other entries in the columns of leading 1s should be zeros.

$\textbf{f. Matrix F:}$
\[
\begin{pmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 & 0 \\
\end{pmatrix}
\]

This matrix is in $\textbf{reduced row echelon form (RREF)}$ because it satisfies all the conditions for RREF mentioned below:
1. In each row, the leftmost nonzero entry is 1.
2. The leading 1 in each row is to the right of the leading 1 in the row above.
3. Rows containing only zeros, if any, are at the bottom.
4. In each column containing a leading 1, all other entries in that column are zeros.

$\textbf{g. Matrix G:}$
\[
\begin{pmatrix}
1 & 2 & 3 \\
1 & 0 & 0 \\
0 & 1 & 1 \\
0 & 0 & 1 \\
\end{pmatrix}
\]

This matrix is in $\textbf{neither row echelon form (REF) nor reduced row echelon form (RREF)}$. While it has leading 1s in rows 2, 3, and 4, it does not satisfy the condition that all other entries in the columns of leading 1s should be zeros.

$\textbf{h. Matrix H:}$
\[
\begin{pmatrix}
2 & 1 & 3 & 5 \\
0 & 0 & 1 & -1 \\
0 & 0 & 0 & 3 \\
0 & 0 & 0 & 0 \\
\end{pmatrix}
\]

This matrix is in $\textbf{neither row echelon form (REF) nor reduced row echelon form (RREF)}$. It has leading 1s in rows 1 and 3, but it does not satisfy the condition that all other entries in the columns of leading 1s should be zeros.


---
5. Solve the following systems of linear equations<br>
a.<br> 
\begin{equation}
x_1+2x_2-3x_3=9 \\
2x_1-x_2-x_3=0 \\
4x_1-x_2+x_3=4 \\
\end{equation}
<br>
<br>


$\textbf{Matrix A:}$
\[
\begin{pmatrix}
1 & 2 & -3 & | & 9 \\
2 & -1 & -1 & | & 0 \\
4 & -1 & 1 & | & 4 \\
\end{pmatrix}
\]

This matrix represents the system of equations. Let's use Gaussian elimination to solve it step by step:

Step 1: Subtract 2 times the first row from the second row and 4 times the first row from the third row to eliminate $x1$ below the first row.

\[
\begin{pmatrix}
1 & 2 & -3 & | & 9 \\
0 & -5 & 5 & | & -18 \\
0 & -9 & 13 & | & -32 \\
\end{pmatrix}
\]

Step 2: Multiply the second row by $-\frac{1}{5}$ to make the leading coefficient of the second row 1.

\[
\begin{pmatrix}
1 & 2 & -3 & | & 9 \\
0 & 1 & -1 & | & 3.6 \\
0 & -9 & 13 & | & -32 \\
\end{pmatrix}
\]

Step 3: Add 9 times the second row to the third row to eliminate $x2$ below the second row.

\[
\begin{pmatrix}
1 & 2 & -3 & | & 9 \\
0 & 1 & -1 & | & 3.6 \\
0 & 0 & 4 & | & -0.4 \\
\end{pmatrix}
\]

Step 4: Divide the third row by 4 to make the leading coefficient of the third row 1.

\[
\begin{pmatrix}
1 & 2 & -3 & | & 9 \\
0 & 1 & -1 & | & 3.6 \\
0 & 0 & 1 & | & -0.1 \\
\end{pmatrix}
\]

Step 5: Subtract $-1$ times the third row from the second row and $3$ times the third row from the first row to eliminate other entries in the column containing the leading 1 in the third row.

\[
\begin{pmatrix}
1 & 2 & 0 & | & 9.3 \\
0 & 1 & 0 & | & 3.7 \\
0 & 0 & 1 & | & -0.1 \\
\end{pmatrix}
\]

Step 6: Subtract $2$ times the third row from the first row to eliminate other entries in the column containing the leading 1 in the third row.

\[
\begin{pmatrix}
1 & 0 & 0 & | & 9.5 \\
0 & 1 & 0 & | & 3.7 \\
0 & 0 & 1 & | & -0.1 \\
\end{pmatrix}
\]

Now, the matrix is in $\textbf{reduced row echelon form (RREF)}$.

The solution to the system of equations is:
\begin{align*}
x1 &= 9.5 \\
x2 &= 3.7 \\
x3 &= -0.1 \\
\end{align*}

So, $x1 = 9.5$, $x2 = 3.7$, and $x3 = -0.1$.


In [16]:
import sympy as sp

x1, x2, x3 = sp.symbols('x1 x2 x3')

eq1 = sp.Eq(x1 + 2*x2 - 3*x3, 9)
eq2 = sp.Eq(2*x1 - x2 - x3, 0)
eq3 = sp.Eq(4*x1 - x2 + x3, 4)

sol = sp.solve((eq1, eq2, eq3), (x1, x2, x3))
print(sol)


{x1: 19/10, x2: 37/10, x3: 1/10}


b. <br>
\begin{equation}
x+2y= -1 \\
2x+y+z = 1 \\
-x+y-z = -1
\end{equation}



Manual Solution (LaTeX):

Forward Elimination:

Representing the system of equations in matrix form:
\[
\begin{bmatrix}
1 & 2 & 0 \\
2 & 1 & 1 \\
-1 & 1 & -1
\end{bmatrix}

\begin{bmatrix}
x \\
y \\
z
\end{bmatrix}
=
\begin{bmatrix}
-1 \\
1 \\
-1
\end{bmatrix}
\]

Using row operations to simplify the augmented matrix:
\[
\begin{bmatrix}
1 & 2 & 0 & | & -1 \\
2 & 1 & 1 & | & 1 \\
-1 & 1 & -1 & | & -1
\end{bmatrix}
\]

Row 2 - 2 * Row 1:
\[
\begin{bmatrix}
1 & 2 & 0 & | & -1 \\
0 & -3 & 1 & | & 3 \\
-1 & 1 & -1 & | & -1
\end{bmatrix}
\]

Row 3 + Row 1:
\[
\begin{bmatrix}
1 & 2 & 0 & | & -1 \\
0 & -3 & 1 & | & 3 \\
0 & 3 & -1 & | & -2
\end{bmatrix}
\]

Row 3 + Row 2:
\[
\begin{bmatrix}
1 & 2 & 0 & | & -1 \\
0 & -3 & 1 & | & 3 \\
0 & 0 & 0 & | & 1
\end{bmatrix}
\]

Now, the system is inconsistent because the last row represents the equation $0z = 1$, which has no solution. Therefore, there is no solution to the system of equations.


In [23]:
import sympy as sp

x, y, z = sp.symbols('x y z')

eq1 = sp.Eq(x + 2*y, -1)
eq2 = sp.Eq(2*x + y + z, 1)
eq3 = sp.Eq(-x + y - z, -1)

sol = sp.solve((eq1, eq2, eq3), (x, y, z))
print(sol)


[]


c. <br>
\begin{equation}
x_1-3x_2-2x_3=0 \\
-x_1+2x_2+x_3=0 \\
2x_1+4x_2+6x_3=0 \\
\end{equation}
<br>


Manual Solution (LaTeX):

Forward Elimination:

Representing the system of equations in matrix form:
\[
\begin{bmatrix}
1 & -3 & -2 \\
-1 & 2 & 1 \\
2 & 4 & 6
\end{bmatrix}

\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}
=
\begin{bmatrix}
0 \\
0 \\
0
\end{bmatrix}
\]

Using row operations to simplify the augmented matrix:
\[
\begin{bmatrix}
1 & -3 & -2 & | & 0 \\
-1 & 2 & 1 & | & 0 \\
2 & 4 & 6 & | & 0
\end{bmatrix}
\]

Row 2 + Row 1:
\[
\begin{bmatrix}
1 & -3 & -2 & | & 0 \\
0 & -1 & -1 & | & 0 \\
2 & 4 & 6 & | & 0
\end{bmatrix}
\]

Row 3 - 2 * Row 1:
\[
\begin{bmatrix}
1 & -3 & -2 & | & 0 \\
0 & -1 & -1 & | & 0 \\
0 & 10 & 10 & | & 0
\end{bmatrix}
\]

Row 3 + 10 * Row 2:
\[
\begin{bmatrix}
1 & -3 & -2 & | & 0 \\
0 & -1 & -1 & | & 0 \\
0 & 0 & 0 & | & 0
\end{bmatrix}
\]

Now, we have a row of zeros in the augmented matrix, indicating that there are infinitely many solutions to the system. We can express the solution in terms of a parameter. Let $t$ be a parameter:

\[
\begin{align*}
x_1 - 3x_2 - 2x_3 &= 0 \\
x_1 &= 3x_2 + 2x_3 \\
x_2 &= -t \\
x_3 &= t
\end{align*}
\]

So, the solution to the system of equations is:
\[
\begin{align*}
x_1 &= 3t - 2t \\
x_1 &= t \\
x_2 &= -t \\
x_3 &= t
\end{align*}
\]

This represents the infinite solutions to the system, where $t$ can take any real value.


In [25]:
import sympy as sp

x1, x2, x3 = sp.symbols('x1 x2 x3')

eq1 = sp.Eq(x1 - 3*x2 - 2*x3, 0)
eq2 = sp.Eq(-x1 + 2*x2 + x3, 0)
eq3 = sp.Eq(2*x1 + 4*x2 + 6*x3, 0)

sol = sp.solve((eq1, eq2, eq3), (x1, x2, x3))
print(sol)


{x1: -x3, x2: -x3}


d. <br>
\begin{equation}
w+x+2y+z=1 \\
w-x-y+z=0 \\
x+y=1 \\
w+x+z=2
\end{equation}
<br>

Manual Solution (LaTeX):

Forward Elimination:

Representing the system of equations in matrix form:
\[
\begin{bmatrix}
1 & 1 & 2 & 1 \\
1 & -1 & -1 & 1 \\
0 & 1 & 1 & 0 \\
1 & 1 & 0 & 1
\end{bmatrix}

\begin{bmatrix}
w \\
x \\
y \\
z
\end{bmatrix}
=
\begin{bmatrix}
1 \\
0 \\
1 \\
2
\end{bmatrix}
\]

Using row operations to simplify the augmented matrix:
\[
\begin{bmatrix}
1 & 1 & 2 & 1 & | & 1 \\
1 & -1 & -1 & 1 & | & 0 \\
0 & 1 & 1 & 0 & | & 1 \\
1 & 1 & 0 & 1 & | & 2
\end{bmatrix}
\]

Row 2 - Row 1:
\[
\begin{bmatrix}
1 & 1 & 2 & 1 & | & 1 \\
0 & -2 & -3 & 0 & | & -1 \\
0 & 1 & 1 & 0 & | & 1 \\
1 & 1 & 0 & 1 & | & 2
\end{bmatrix}
\]

Row 4 - Row 1:
\[
\begin{bmatrix}
1 & 1 & 2 & 1 & | & 1 \\
0 & -2 & -3 & 0 & | & -1 \\
0 & 1 & 1 & 0 & | & 1 \\
0 & 0 & -2 & 0 & | & 1
\end{bmatrix}
\]

Row 2 * (-1/2):
\[
\begin{bmatrix}
1 & 1 & 2 & 1 & | & 1 \\
0 & 1 & 3/2 & 0 & | & 1/2 \\
0 & 1 & 1 & 0 & | & 1 \\
0 & 0 & -2 & 0 & | & 1
\end{bmatrix}
\]

Row 3 - Row 2:
\[
\begin{bmatrix}
1 & 1 & 2 & 1 & | & 1 \\
0 & 1 & 3/2 & 0 & | & 1/2 \\
0 & 0 & -1/2 & 0 & | & 1/2 \\
0 & 0 & -2 & 0 & | & 1
\end{bmatrix}
\]

Row 4 * (-1/2):
\[
\begin{bmatrix}
1 & 1 & 2 & 1 & | & 1 \\
0 & 1 & 3/2 & 0 & | & 1/2 \\
0 & 0 & -1/2 & 0 & | & 1/2 \\
0 & 0 & 1 & 0 & | & -1/2
\end{bmatrix}
\]

Row 3 * (-2):
\[
\begin{bmatrix}
1 & 1 & 2 & 1 & | & 1 \\
0 & 1 & 3/2 & 0 & | & 1/2 \\
0 & 0 & 1 & 0 & | & -1 \\
0 & 0 & 1 & 0 & | & -1/2
\end{bmatrix}
\]

Row 4 - Row 3:
\[
\begin{bmatrix}
1 & 1 & 2 & 1 & | & 1 \\
0 & 1 & 3/2 & 0 & | & 1/2 \\
0 & 0 & 1 & 0 & | & -1 \\
0 & 0 & 0 & 0 & | & 1/2
\end{bmatrix}
\]

Now, the system is inconsistent because the last row represents the equation $0z = 1/2$, which has no solution. Therefore, there is no solution to the system of equations.

This concludes the forward elimination steps.


In [20]:
import sympy as sp

w, x, y, z = sp.symbols('w x y z')

eq1 = sp.Eq(w + x + 2*y + z, 1)
eq2 = sp.Eq(w - x - y + z, 0)
eq3 = sp.Eq(x + y, 1)
eq4 = sp.Eq(w + x + z, 2)

sol = sp.solve((eq1, eq2, eq3, eq4), (w, x, y, z))
print(sol)


[]


---
6. Determine if the vectors are linear combinations<br>
a. <br>
 \begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} -1 \\ 3 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 2 \\ -6 \end{bmatrix}\\
\end{equation}


$$
\begin{aligned}
\textbf{v} &= \begin{bmatrix} 1 \\ 2 \end{bmatrix}, \\
\textbf{u}_2 &= \begin{bmatrix} -1 \\ 3 \end{bmatrix}, \\
\textbf{u}_3 &= \begin{bmatrix} 2 \\ -6 \end{bmatrix}
\end{aligned}
$$

To determine if $\textbf{v}$ can be expressed as a linear combination of $\textbf{u}_2$ and $\textbf{u}_3$, we need to find values for $x$ and $y$ such that:

$$
x \textbf{u}_2 + y \textbf{u}_3 = \textbf{v}
$$

This leads to the following system of equations:

\begin{align*}
-x + 2y &= 1 \\
3x - 6y &= 2
\end{align*}

We can represent this system as an augmented matrix and perform row operations:

$$
\begin{bmatrix}
-1 & 2 & | & 1 \\
3 & -6 & | & 2
\end{bmatrix}
\xrightarrow{\text{R}_{2} + 3\text{R}_{1} \rightarrow \text{R}_{2}}
\begin{bmatrix}
-1 & 2 & | & 1 \\
0 & 0 & | & 5
\end{bmatrix}
$$

Since the last row implies $0 = 5$, the system is inconsistent. Therefore, vector $\textbf{v}$ cannot be expressed as a linear combination of $\textbf{u}_2$ and $\textbf{u}_3$.


b. <br>
\begin{equation}
    \textbf{v} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}



$$
\begin{aligned}
\textbf{v} &= \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}, \\
\textbf{u}_2 &= \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}, \\
\textbf{u}_3 &= \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}
\end{aligned}
$$

To check if $\textbf{v}$ can be expressed as a linear combination of $\textbf{u}_2$ and $\textbf{u}_3$, we need to find values for $x$, $y$, and $z$ such that:

$$
x \textbf{u}_2 + y \textbf{u}_3 = \textbf{v}
$$

This leads to the following system of equations:

\begin{align*}
x + 0z &= 1 \\
x + y &= 2 \\
0 + y &= 3
\end{align*}

We can represent this system as an augmented matrix and perform row operations:

$$
\begin{bmatrix}
1 & 0 & 0 & | & 1 \\
1 & 1 & 0 & | & 2 \\
0 & 1 & 1 & | & 3
\end{bmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{bmatrix}
1 & 0 & 0 & | & 1 \\
0 & 1 & 0 & | & 1 \\
0 & 1 & 1 & | & 3
\end{bmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
\begin{bmatrix}
1 & 0 & 0 & | & 1 \\
0 & 1 & 0 & | & 1 \\
0 & 0 & 1 & | & 2
\end{bmatrix}
$$

The system has a unique solution: $x = 1$ and $y = 1$. Therefore, the vector $\textbf{v}$ can be expressed as a linear combination of $\textbf{u}_2$ and $\textbf{u}_3$.


c. <br>
\begin{equation}
    \textbf{v} = \begin{bmatrix} 3 \\ 1 \\ -2 \end{bmatrix} \ 
    \textbf{u}_2 = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}\
    \textbf{u}_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\\
\end{equation}


$$
\begin{aligned}
\textbf{v} &= \begin{bmatrix} 3 \\ 1 \\ -2 \end{bmatrix}, \\
\textbf{u}_2 &= \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}, \\
\textbf{u}_3 &= \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}
\end{aligned}
$$

To determine if <span class="math-inline">\\textbf\{v\}</span> can be expressed as a linear combination of <span class="math-inline">\\textbf\{u\}\_2</span> and <span class="math-inline">\\textbf\{u\}\_3</span>, we need to find values for <span class="math-inline">x</span>, <span class="math-inline">y</span>, and <span class="math-inline">z</span> such that:

$$
x \textbf{u}_2 + y \textbf{u}_3 = \textbf{v}
$$

This leads to the following system of equations:

\begin{align*}
x + 0z &= 3 \\
x + y &= 1 \\
0 + y &= -2
\end{align*}

We can represent this system as an augmented matrix and perform row operations:

$$
\begin{bmatrix}
1 & 0 & 0 & | & 3 \\
1 & 1 & 0 & | & 1 \\
0 & 1 & 1 & | & -2
\end{bmatrix}
\xrightarrow{\text{R}_{2} - \text{R}_{1}}
\begin{bmatrix}
1 & 0 & 0 & | & 3 \\
0 & 1 & 0 & | & -2 \\
0 & 1 & 1 & | & -2
\end{bmatrix}
\xrightarrow{\text{R}_{3} - \text{R}_{2}}
\begin{bmatrix}
1 & 0 & 0 & | & 3 \\
0 & 1 & 0 & | & -2 \\
0 & 0 & 1 & | & 0
\end{bmatrix}
$$

Now, the system is consistent and has infinitely many solutions. Therefore, vector <span class="math-inline">\\textbf\{v\}</span> is a linear combination of <span class="math-inline">\\textbf\{u\}\_2</span> and <span class="math-inline">\\textbf\{u\}\_3</span>, and there are multiple solutions for <span class="math-inline">x</span> and <span class="math-inline">y</span>.


---
7. Show that the following vectors are a span: <br>
a.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 1 \\ \end{bmatrix}
\begin{bmatrix}1 \\ -1 \\ \end{bmatrix}
\end{pmatrix}
$
<br><br>
Manual Solution:

We have the augmented matrix:
\[
\begin{bmatrix}
1 & 1 & | & x \\
1 & -1 & | & y
\end{bmatrix}
\]

Performing row operations, we get:
\[
\begin{bmatrix}
\begin{array}{cccc|c}
1 & 1 & | & x & (R_1) \\
1 & -1 & | & y & (R_2)
\end{array}
\end{bmatrix}
\xrightarrow{\text{R}_{2} -\text{R}_{1}}
\begin{bmatrix}
\begin{array}{cccc|c}
1 & 1 & | & x & (R_1) \\
0 & -2 & | & y - x & (R_2 - R_1)
\end{array}
\end{bmatrix}
\xrightarrow{\frac{1}{-2}\text{R}_{2}}
\begin{bmatrix}
\begin{array}{cccc|c}
1 & 1 & | & x & (R_1) \\
0 & 1 & | & \frac{y - x}{-2} & \left(\frac{1}{-2}\right)R_2
\end{array}
\end{bmatrix}
\]

The given vectors are a span.

b.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
\begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
\begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
\end{pmatrix}
$
Manual Solution:

Given the system of equations:
\begin{align*}
a + b &= x \\
b + c &= y \\
a + c &= z
\end{align*}

We can represent this system as an augmented matrix:
\[
\begin{bmatrix}
1 & 1 & 0 & | & x \\
0 & 1 & 1 & | & y \\
1 & 0 & 1 & | & z
\end{bmatrix}
\]

Applying row operations, we obtain:
\[
\begin{bmatrix}
1 & 1 & 0 & | & x \\
0 & 1 & 1 & | & y \\
0 & -1 & 1 & | & z - x
\end{bmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{2}}
\begin{bmatrix}
1 & 1 & 0 & | & x \\
0 & 1 & 1 & | & y \\
0 & 0 & 2 & | & y - x + z
\end{bmatrix}
\]

The vectors are a span as long as \(2\) divides \(y - x + z\).

<br><br>

c.<br>
$
span\begin{pmatrix}
\begin{bmatrix}1 \\ 0 \\ 1\end{bmatrix}
\begin{bmatrix}1 \\ 1 \\ 0\end{bmatrix}
\begin{bmatrix}0 \\ 1 \\ 1\end{bmatrix}
\end{pmatrix}
$
Manual Solution:

Given the system of equations:
\begin{align*}
a + b &= x \\
b + c &= y \\
a + c &= z
\end{align*}

We can represent this system as an augmented matrix:
\[
\begin{bmatrix}
1 & 1 & 0 & | & x \\
0 & 1 & 1 & | & y \\
1 & 0 & 1 & | & z
\end{bmatrix}
\]

Applying row operations, we obtain:
\[
\begin{bmatrix}
1 & 1 & 0 & | & x \\
0 & 1 & 1 & | & y \\
0 & -1 & 1 & | & z - x
\end{bmatrix}
\xrightarrow{\text{R}_{3} + \text{R}_{2}}
\begin{bmatrix}
1 & 1 & 0 & | & x \\
0 & 1 & 1 & | & y \\
0 & 0 & 2 & | & y - x + z
\end{bmatrix}
\]

The vectors are a span as long as \(2\) divides \(y - x + z\).

<br><br>


---
8. Show that the following vectors are linearly independent:<br>
a. <br>
\begin{align*}
\begin{bmatrix} 3 \\ -1 \\ 1 \\ -1 \end{bmatrix},
\begin{bmatrix} -1 \\ 2 \\ 1 \\ -1 \end{bmatrix},
\begin{bmatrix} 1 \\ 1 \\ 3 \\ 1 \end{bmatrix},
\begin{bmatrix} -1 \\ -1 \\ 1 \\ 3 \end{bmatrix}
\end{align*}
To show that the following vectors are linearly independent:

\[
\begin{bmatrix} 3 \\ -1 \\ 1 \\ -1 \end{bmatrix},
\begin{bmatrix} -1 \\ 2 \\ 1 \\ -1 \end{bmatrix},
\begin{bmatrix} 1 \\ 1 \\ 3 \\ 1 \end{bmatrix},
\begin{bmatrix} -1 \\ -1 \\ 1 \\ 3 \end{bmatrix}
\]

We have \(m = 4\) (number of vectors) and \(n = 4\) (dimension of vectors).

According to the conditions for linear independence:

Condition 3: If \(m > n\), then the vectors are linearly dependent. Here, \(4 \nless 4\), so this condition is not met.

Condition 4: If the determinant of the matrix formed by these vectors is nonzero, then the vectors are linearly independent.

Using these conditions, we can conclude that the given vectors are linearly independent.

b. <br>
\begin{equation}
\begin{bmatrix} 0 \\ 0 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 0 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 0 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\begin{bmatrix} 4 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\end{equation}
To show that the following vectors are linearly independent:

\[
\begin{bmatrix} 0 \\ 0 \\ 0 \\ 1 \end{bmatrix},
\begin{bmatrix} 0 \\ 0 \\ 2 \\ 1 \end{bmatrix},
\begin{bmatrix} 0 \\ 3 \\ 2 \\ 1 \end{bmatrix},
\begin{bmatrix} 4 \\ 3 \\ 2 \\ 1 \end{bmatrix}
\]

We have \(m = 4\) (number of vectors) and \(n = 4\) (dimension of vectors).

Using the conditions for linear independence:

L1: \(4z = 0\), implies \(z = 0\).
L2: \(3w + 3z = 0\), implies \(w = 0\).
L3: \(2y + 2w + 2z = 0\), implies \(y = 0\).
L4: \(x + 0 + 0 + 0 = 0\), implies \(x = 0\).

Therefore, all the scalar coefficients are zero, satisfying condition 1 for linear independence. Hence, the vectors are linearly independent.

<br>
c. <br>
\begin{equation}
\begin{bmatrix} 1 \\ -1 \\ 1 \\ 0 \end{bmatrix}
\begin{bmatrix} -1 \\ 1 \\ 0 \\ 1 \end{bmatrix}
\begin{bmatrix} 1 \\ 0 \\ 1 \\ -1 \end{bmatrix}
\begin{bmatrix} 0 \\ 1 \\ -1 \\ 1 \end{bmatrix}
\end{equation}
To show that the following vectors are linearly independent:

\[
\begin{bmatrix} 1 \\ -1 \\ 1 \\ 0 \end{bmatrix},
\begin{bmatrix} -1 \\ 1 \\ 0 \\ 1 \end{bmatrix},
\begin{bmatrix} 1 \\ 0 \\ 1 \\ -1 \end{bmatrix},
\begin{bmatrix} 0 \\ 1 \\ -1 \\ 1 \end{bmatrix}
\]

We have \(m = 4\) (number of vectors) and \(n = 4\) (dimension of vectors).

According to condition 4, if \(m = n\), the vectors are linearly independent.

Since \(m = 4\) and \(n = 4\), the vectors are linearly independent by condition 4.
